In [1]:
import pandas as pd
df=pd.read_csv("C:\\Users\\Shadab\\OneDrive\\Documents\\Project3\\smart_logistics_dataset.csv")
df.head()

,Timestamp,Asset_ID,Latitude,Longitude,Inventory_Level,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Logistics_Delay_Reason,Asset_Utilization,Demand_Forecast,Logistics_Delay
0,2024-03-20 00:11:14,Truck_7,-65.7383,11.2497,390,Delayed,27.0,67.8,Detour,38,320,4,NaN,60.1,285,1
1,2024-10-30 07:53:51,Truck_6,22.2748,-131.7086,491,In Transit,22.5,54.3,Heavy,16,439,7,Weather,80.9,174,1
2,2024-07-29 18:42:48,Truck_10,54.9232,79.5455,190,In Transit,25.2,62.2,Detour,34,355,3,NaN,99.2,260,0
3,2024-10-28 00:50:54,Truck_9,42.3900,-1.4788,330,Delivered,25.4,52.3,Heavy,37,227,5,Traffic,97.4,160,1
4,2024-09-27 15:52:58,Truck_7,-65.8477,47.9468,480,Delayed,20.5,57.2,Clear,56,197,6,NaN,71.6,270,1

In [2]:
df.describe()

,Latitude,Longitude,Inventory_Level,Temperature,Humidity,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Asset_Utilization,Demand_Forecast,Logistics_Delay
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,-1.360093,0.837049,297.915000,23.893900,65.042200,35.062000,299.055000,5.513000,79.599100,199.284000,0.566000
std,51.997183,104.843618,113.554773,3.322178,8.753765,14.477768,117.787792,2.935379,11.631153,59.920847,0.495873
min,-89.791500,-179.820200,100.000000,18.000000,50.000000,10.000000,100.000000,1.000000,60.000000,100.000000,0.000000
25%,-46.167975,-88.448075,201.000000,21.200000,57.200000,23.000000,191.750000,3.000000,69.475000,144.000000,0.000000
50%,-4.503150,0.678300,299.000000,23.800000,65.200000,35.000000,301.500000,6.000000,79.250000,202.000000,1.000000
75%,44.502800,88.156450,399.000000,26.600000,72.400000,49.000000,405.000000,8.000000,89.425000,251.250000,1.000000
max,89.870100,179.923700,500.000000,30.000000,80.000000,60.000000,500.000000,10.000000,100.000000,300.000000,1.000000

In [3]:
df.shape

(1000, 16)

In [4]:
df.isnull().sum()

Timestamp                    0
Asset_ID                     0
Latitude                     0
Longitude                    0
Inventory_Level              0
Shipment_Status              0
Temperature                  0
Humidity                     0
Traffic_Status               0
Waiting_Time                 0
User_Transaction_Amount      0
User_Purchase_Frequency      0
Logistics_Delay_Reason     263
Asset_Utilization            0
Demand_Forecast              0
Logistics_Delay              0
dtype: int64

In [5]:
null_value=df['Logistics_Delay_Reason'].mode()[0]
df['Logistics_Delay_Reason']=df['Logistics_Delay_Reason'].fillna(null_value)

In [6]:
df.isnull().sum()

Timestamp                  0
Asset_ID                   0
Latitude                   0
Longitude                  0
Inventory_Level            0
Shipment_Status            0
Temperature                0
Humidity                   0
Traffic_Status             0
Waiting_Time               0
User_Transaction_Amount    0
User_Purchase_Frequency    0
Logistics_Delay_Reason     0
Asset_Utilization          0
Demand_Forecast            0
Logistics_Delay            0
dtype: int64

In [7]:
df.columns=df.columns.str.lower()
df.columns

Index(['timestamp', 'asset_id', 'latitude', 'longitude', 'inventory_level',
       'shipment_status', 'temperature', 'humidity', 'traffic_status',
       'waiting_time', 'user_transaction_amount', 'user_purchase_frequency',
       'logistics_delay_reason', 'asset_utilization', 'demand_forecast',
       'logistics_delay'],
      dtype='str')

In [8]:
def asset_utilization_category(x):
    if 60<= x <=70:
        return "Low Utilization"
    elif 71<= x <= 85:
        return "Medium Utilization"
    elif 86<= x <=100:
        return "High Utilization"
    else:
        return "Outside Range"

df['asset_utilization_category']=df['asset_utilization'].apply(asset_utilization_category)

In [9]:
df[['asset_utilization','asset_utilization_category']]

     asset_utilization asset_utilization_category
0                 60.1            Low Utilization
1                 80.9         Medium Utilization
2                 99.2           High Utilization
3                 97.4           High Utilization
4                 71.6         Medium Utilization
..                 ...                        ...
995               79.2         Medium Utilization
996               83.7         Medium Utilization
997               74.8         Medium Utilization
998               88.6           High Utilization
999               81.3         Medium Utilization

[1000 rows x 2 columns]

In [10]:
df['timestamp']=pd.to_datetime(df['timestamp'])

In [11]:
df['month_name']=df['timestamp'].dt.month_name()
df['month']=df['timestamp'].dt.month
df['week']=df['timestamp'].dt.isocalendar().week
df['day']=df['timestamp'].dt.day
df['day_of_week']=df['timestamp'].dt.day_name()
df['hour']=df['timestamp'].dt.hour
df['date']=df['timestamp'].dt.date

df[['month_name','month','week','day','day_of_week','hour','date']]

    month_name  month  week  day day_of_week  hour        date
0        March      3    12   20   Wednesday     0  2024-03-20
1      October     10    44   30   Wednesday     7  2024-10-30
2         July      7    31   29      Monday    18  2024-07-29
3      October     10    44   28      Monday     0  2024-10-28
4    September      9    39   27      Friday    15  2024-09-27
..         ...    ...   ...  ...         ...   ...         ...
995       July      7    30   22      Monday    16  2024-07-22
996      April      4    18   30     Tuesday     4  2024-04-30
997    October     10    43   27      Sunday    22  2024-10-27
998      April      4    16   18    Thursday    23  2024-04-18
999  September      9    38   18   Wednesday    19  2024-09-18

[1000 rows x 7 columns]

In [12]:
def purchase_frequency_category(x):
    if 1<=x<=3:
        return "Low"
    elif 4<=x<=7:
        return "Medium"
    else:
        return "High"

df['purchase_frequency_category']=df['user_purchase_frequency'].apply(purchase_frequency_category)
df[['purchase_frequency_category','user_purchase_frequency']]

    purchase_frequency_category  user_purchase_frequency
0                        Medium                        4
1                        Medium                        7
2                           Low                        3
3                        Medium                        5
4                        Medium                        6
..                          ...                      ...
995                         Low                        1
996                      Medium                        7
997                      Medium                        5
998                      Medium                        5
999                        High                        9

[1000 rows x 2 columns]

In [13]:
#Exporting the cleaned data:
df.to_csv('smart_logistics_dataset.csv', index= False)

In [14]:
from sqlalchemy import create_engine
# Defining my database credentials:
USER = "root"
PASSWORD = "Sarfu123"
HOST = "127.0.0.1"       
PORT = "3306"           
DATABASE = "smart_logistics_and_supply_chain"

# Creating the SQLAlchemy engine connection string:
connection_string = f"mysql+pymysql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
engine = create_engine(connection_string)

In [15]:
# Uploading the DataFrame to MySQL:
df.to_sql(
    name='logistics',         
    con=engine,              
    if_exists='append',     
    index=False             
)

1000